security:
  oauth2:
    client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d

server:
  port: 7002
  servlet:
    context-path: /auth
user:
  oauth:
    clientId: R2dpxQ3vPrtfgF72
    clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
    redirectUris: http://localhost:7002/login/redirect
    user:
      username: admin2
      password: nucleus

logging:
  level:
    org:
      springframework: DEBUG
